name: Deploy
on: push
#on:
#  push:
#    branches:
#      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker HUB
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo ${DOCKERHUB_PASSWORD} | docker login --username ${DOCKERHUB_USER} --password-stdin
      - name: Build and push docker image
        run: |
          docker build -t ysku/my-k8s-custom-controller .
          docker tag ysku/my-k8s-custom-controller ysku/my-k8s-custom-controller:${{ github.sha }}
          # create new image with tag
          docker push ysku/my-k8s-custom-controller:${{ github.sha }}
          # update latest
          docker push ysku/my-k8s-custom-controller
